# Uncomment the next line to define a global platform for your project
platform :ios, '10.6'

use_frameworks!

def share_pods
 	 pod 'JTAppleCalendar'
  	 pod 'Moya/RxSwift'
	 pod 'RxSwift'
	 pod 'RxCocoa'
end


target 'SubscriptionManagement' do
	share_pods

end

target 'SubscriptionWidgetExtension' do
	share_pods

end